### ISSUE TITLE
Kademlia

### ISSUE THREAD

**Issue by arni077** [datproject/dat#1017]
I am reporting:

- [ ] a bug or unexpected behavior
- [] general feedback
- [ ] feature request
- [x] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: 
* Node Version:
* Dat Version: 13.10.0

I read the whitepaper and since I understand Dat using original Kademlia design then how Dat handles number of attacks such as DDOS or sybil and/or churn?

**Comment by maxogden** [comment]
We use kademlia as one discovery method for connection candidates. But then the protocol itself uses the public key (in the dat:// link) to verify the integrity of data being received. Dat is messaged based (protocol buffers) and uses UTP or TCP as the transport protocols. We opt for UTP, which has better DDOS protection than say HTTPS by default due to less statefulness.

One attack is that someone could spam fake entries in the DHT therefore making it difficult to find valid peers, so thats why we have a modular design in regard to discovery methods. Currently Dat also uses a set of DNS servers in addition to the DHT for peer discovery.

**Comment by arni077** [comment]
Why not S/Kademlia ?

**Comment by maxogden** [comment]
Yes it would be interesting to see other approaches. I believe S/Kademlia describes the general idea of signing DHT entries but does not specify it as a RFC, and I do not believe there is an implementation in JavaScript. However if you know of one you can implement other providers by adding them to this module https://github.com/maxogden/discovery-channel. You could take the Dat keypair and use the S/Kademlia signature schemes.

**Comment by arni077** [comment]
[SKademlia - Practicable Approach Towards Secure Key Based Routing.pdf](https://github.com/datproject/dat/files/2182445/SKademlia.-.Practicable.Approach.Towards.Secure.Key.Based.Routing.pdf)

**Comment by arni077** [comment]
@pfrazee I would like your opinion on this.

**Comment by pfrazee** [comment]
I don't hold a strong opinion yet on the right solution. We're researching different things, not just around security, but also privacy and reliability. SKademlia should be one of the things we look at.
