### ISSUE TITLE
Why could IPFS run in China but Dat had issues?

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1076]
@Blurhy said he could run IPFS on its country (China), but could!'t run Dat. What is the reason?

**Comment by thadguidry** [comment]
The primary reason is that IPFS is transport agnostic and supports NAT traversal, Encryption, just to name a few.  IPFS can run over any transport protocol and does not even depend on IP, in fact.
https://github.com/libp2p/specs
So it's easier for IPFS communication to happen between peers and relays.
China's Great Firewall blocks at the HTTP transport layer when it can understand the context (which is why a VPN connection can easily punch through and how many in China reach blocked resources)
With IPFS that becomes nearly impossible to block given it can work over so many different transport and network protocols.

**Comment by DaniellMesquita** [comment]
So, can Dat run through IPFS? And also use ZeroNet on the same IPFS?

**Comment by blurHY** [comment]
Unfortunately, GFW can detect  IPFS traffic now

**Comment by joehand** [comment]
You should be able to run Dat on libp2p, yes.
