### ISSUE TITLE
Hard coded path separator for 'created new dat' string

### ISSUE THREAD

**Issue by deed02392** [datproject/dat#930]
https://github.com/datproject/dat/blob/9a7150a10a7b312d408e2c223608eaea6d21f213/src/ui/archive.js#L23

Forward slash is not a path separator on Windows. Need to use some Node module to get the current platforms path sep char.

**Comment by flurbius** [comment]
Hi, am I overqualified for this?  I just found this project and I'm thinking what an awesome project I would love to contribute but this issue looks like its been set aside as an easy entry for someone.

It could be easily solved by adding a package but maybe you don't want an extra dependency and since its a small task it could be solved without the package in a line or two of code.

**Comment by joehand** [comment]
Go for it if you'd like =). Yes, should be able to accomplish with the core `path` module afaik.

**Comment by flurbius** [comment]
OK, I've just had a look at it and it's done but then it occured to me to look around to see if there was anywhere else it was needed and I noticed that there is a lot of linux style line endings.  It is a different package but that should probably be changed as well.

**Comment by joehand** [comment]
Thanks! 

Ya, we did not have windows support for a long time and I was not great at thinking about that =/.
