### ISSUE TITLE
Add custom metadata to the history log

### ISSUE THREAD

**Issue by mitar** [datproject/dat#943]
To track changes to datasets it would be great if I could add some extra metadata to history log: for example a textual description about the change, an author, timestamp? Similar to how git has it. But also so that datasets used in science would have a clear log of changes to it with sources of those changes.

**Comment by pfrazee** [comment]
One thing that we've been sitting on is the idea of 'checkpoints', where you can basically mark a point in the log with a version label and potentially write a message. We probably need to wait for multi-writer to land first, so that we can figure out how those labels will work with multiple authors.

**Comment by okdistribute** [comment]
I think this is out of the scope of dat for the forseeable future, but please check out radicle.xyz or http://cobox.cloud/
