### ISSUE TITLE
Need more document on network condition when dat works and when not

### ISSUE THREAD

**Issue by mumutu66** [datproject/dat#961]
I am new to dat .  and I want to know 
* network condition when it works and when not 
  * where UTP TCP can work? 
  * where node can ping the `discovery1.publicbits.org` ? 
* how to improve it 
  * can dat uses a middle node to bridge each other ?

I tested it with few of my friends from different place
* either of nodes has a public ip works well
* both of nodes using NAT sometimes  works sometime not which is confused me 

thanks very much.

**Comment by joehand** [comment]
Hi! Yes, it depends on the network restrictions and any firewalls. It's a bit hard to document because each network is unique. But we're working on more ways to make this clear.

The first step (discovery) tries a few things:

* DNS Discovery (via discovery1.publicbits.org)
* DHT Discovery
* MDNS Discovery

> can dat uses a middle node to bridge each other ?

Yes! We'd love to have a [TURN](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT) for this.

The networking and discovery all happens in https://github.com/mafintosh/discovery-swarm/.

**Comment by mumutu66** [comment]
Thanks!!
